name: sub_merge

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0/2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: emigrate code
        uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          check-latest: true
      - name: load cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: install dependencies
        run: |
          pip install -r ./.github/requirements.txt
      - name: starting run
        run: |
          rm -rf ./subscription/others/list/* && rm -rf ./subscription/*.yaml
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          python ./utils/list_merge.py
      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f ./subscription
          git add ./Country.mmdb
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') Merge Nodes"

      - name: push
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.TOKEN }}
          branch: main